services:

  db:
    image: postgres
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres1
      POSTGRES_PASSWORD: admin1
      POSTGRES_DB: callforpapers