# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: callforpapers
          POSTGRES_USER: postgres1
          POSTGRES_PASSWORD: admin1
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres1" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Generate JWT Keys
      run: |
        openssl genrsa -out src/main/resources/app.key 2048
        openssl rsa -in src/main/resources/app.key -pubout -out src/main/resources/app.pub

    - name: Build with Maven using application-ci.properties
      run: mvn -B package --file pom.xml -Dspring.config.location=classpath:application-ci.properties -Djwt.private.key=classpath:app.key -Djwt.public.key=classpath:app.pub
      env:
        SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/callforpapers
        SPRING_DATASOURCE_USERNAME: postgres1
        SPRING_DATASOURCE_PASSWORD: admin1
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
        SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
